# Generated by Django 3.2.19 on 2023-07-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlist_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='size',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
