# Generated by Django 3.2.19 on 2023-07-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlist_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
