# Generated by Django 3.2.19 on 2023-07-12 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20230711_2349'),
        ('products', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='wishlist.wishlist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
